export const CONFIG_CONSTANTS = {
  LAYOUT: {
    APP_NAME: 'LAYOUT.APP_NAME',
    FOOTER_ENABLED: 'LAYOUT.FOOTER_ENABLED',
    SIDEBAR_ENABLED: 'LAYOUT.SIDEBAR_ENABLED',
    FLOATING_SIDEBAR: 'LAYOUT.FLOATING_SIDEBAR',
    TOPBAR_SWITCH_THEME_ENABLED: 'LAYOUT.TOPBAR_SWITCH_THEME_ENABLED',
    TOPBAR_THEME_CONFIGURATOR_ENABLED: 'LAYOUT.TOPBAR_THEME_CONFIGURATOR_ENABLED',
    TOPBAR_ACTIONS_ENABLED: 'LAYOUT.TOPBAR_ACTIONS_ENABLED',
    THEME_PRESET: 'LAYOUT.THEME_PRESET',
    THEME_PRIMARY: 'LAYOUT.THEME_PRIMARY',
    THEME_SURFACE: 'LAYOUT.THEME_SURFACE',
    THEME_DARK_THEME: 'LAYOUT.THEME_DARK_THEME',
    THEME_MENU_MODE: 'LAYOUT.THEME_MENU_MODE'
  }
}