export const CONFIG_CONSTANTS = {
  APP_NAME: 'APP_NAME',
  LAYOUT: {
    FOOTER_ENABLED: 'LAYOUT.FOOTER_ENABLED',
    SIDEBAR_ENABLED: 'LAYOUT.SIDEBAR_ENABLED',
    SIDEBAR_FLOATING: 'LAYOUT.SIDEBAR_FLOATING',
    SIDEBAR_USER_AVATAR_ENABLED: 'LAYOUT.SIDEBAR_USER_AVATAR_ENABLED',
    TOPBAR_THEME_CONFIGURATOR_ENABLED: 'LAYOUT.TOPBAR_THEME_CONFIGURATOR_ENABLED',
    TOPBAR_ACTIONS_ENABLED: 'LAYOUT.TOPBAR_ACTIONS_ENABLED',
    TOPBAR_USER_AVATAR_ENABLED: 'LAYOUT.TOPBAR_USER_AVATAR_ENABLED',
    THEME_PRESET: 'LAYOUT.THEME_PRESET',
    THEME_PRIMARY: 'LAYOUT.THEME_PRIMARY',
    THEME_SURFACE: 'LAYOUT.THEME_SURFACE',
    THEME_DARK_THEME: 'LAYOUT.THEME_DARK_THEME',
    THEME_MENU_MODE: 'LAYOUT.THEME_MENU_MODE'
  }
}