export * from './access.interface';
export * from './crud.interface';
export * from './error.interface';
export * from './input-error.interface';
export * from './loader.interface';
export * from './notfound.interface';
export * from './spinner.interface';
export * from './toast.interface';
export * from './translate.interface';
